# This file created by conda-build 2.1.13
#
# This file, and the associated build.sh file do
# not appear to work on later versions of
# conda-build
# ------------------------------------------------

package:
    name: cclib
    version: '1.6.1.rmg'
source:
    git_url: https://github.com/amarkpayne/cclib.git

requirements:
    build:
        - python=3
        - numpy
        - six
        - scipy
        - biopython
        - openbabel
    run:
        - python=3
        - numpy
        - six
        - scipy
        - biopython
        - openbabel
test:
    imports:
        - cclib
        - cclib.io
        - cclib.bridge
        - cclib.method
        - cclib.parser
        - cclib.progress
about:
    home: http://cclib.github.io/
    license: GNU Library or Lesser General Public License (LGPL)
    summary: 'cclib: parsers and algorithms for computational chemistry'
extra:
    final: true
