{% set name = "acat" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acat-{{ version }}.tar.gz
  sha256: 81cb8ddca4730b330be9f877dc8691d1f3cff40e0763a05cc334f354cffdea87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - ase
    - networkx >=2.4
    - python >=3.6
    - setuptools

test:
  imports:
    - acat

about:
  home: https://gitlab.com/asm-dtu/acat
  summary: Alloy Catalysis Automated Toolkit
  license: LGPL-3.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - mjohnson541
